"""Analytical and empirical electrochemical equations.

This subpackage provides closed-form solutions, asymptotic expansions, and empirical
models for electrochemical systems. These analytical equations serve as:
1. Exact ground-truth benchmarks for numerical PDE solvers (:mod:`softpotato.solver`).
2. Rapid parameter estimation tools for experimental and simulated data.
3. Diagnostic baselines for transient, steady-state, and voltammetric responses.

Submodules
----------
fitting : Parameter fitting and experimental data analysis utilities.
hydrodynamics : Convection and hydrodynamic equations for RDE and RRDE.
kinetics : Thermodynamics and interfacial kinetics (Nernst, Butler–Volmer, Tafel).
microelectrodes : Steady-state and transient models for microelectrodes and UMEs.
secm : Scanning Electrochemical Microscopy (SECM) approach curves.
step : Potential and current step equations (Cottrell, Anson, Sand, etc.).
voltammetry : Voltammetry and kinetic diagnostics (Randles–Ševčík, Nicholson, Matsuda–Ayabe).
"""

from . import fitting, hydrodynamics, kinetics, microelectrodes, secm, step, voltammetry
from .fitting import (
    ButlerVolmerFitResult,
    CottrellFitResult,
    FitResult,
    KouteckyLevichFitResult,
    LevichFitResult,
    MicrodiscFitResult,
    RandlesSevcikFitResult,
    SECMApproachFitResult,
    TafelFitResult,
    fit_butler_volmer,
    fit_cottrell,
    fit_curve,
    fit_koutecky_levich,
    fit_levich,
    fit_linear,
    fit_microdisc_transient,
    fit_randles_sevcik,
    fit_secm_approach,
    fit_tafel,
)
from .hydrodynamics import (
    KouteckyLevichResult,
    RRDEResult,
    collection_efficiency,
    koutecky_levich,
    koutecky_levich_analysis,
    levich,
    levich_constant,
    nernst_diffusion_layer,
    rad_s_to_rpm,
    ring_collection_current,
    ring_limiting_current,
    rotating_ring_disk,
    rpm_to_rad_s,
    shielding_factor,
)
from .kinetics import (
    TafelResult,
    butler_volmer,
    butler_volmer_current_density,
    butler_volmer_linear,
    charge_transfer_resistance,
    exchange_current,
    exchange_current_density,
    nernst,
    nernst_equilibrium_concentrations,
    nernst_potential,
    nernst_ratio,
    tafel,
    tafel_analysis,
    tafel_overpotential,
    tafel_slope,
)
from .microelectrodes import (
    mahon_oldham_transient,
    microband_limiting_current,
    microdisc_limiting_current,
    microdisc_transient,
    microhemisphere_limiting_current,
    microsphere_limiting_current,
)
from .secm import (
    secm_approach_curve,
    secm_approach_negative_feedback,
    secm_approach_positive_feedback,
    secm_limiting_current_infinite,
    secm_tip_current,
)
from .step import (
    anson,
    cottrell,
    cottrell_cylinder,
    cottrell_spherical,
    cottrell_step,
    sand,
    sand_potential,
    sand_transition_time,
    step_concentration_profile,
    step_flux_profile,
)
from .voltammetry import (
    MatsudaAyabeResult,
    NicholsonResult,
    matsuda_ayabe,
    matsuda_ayabe_lambda,
    nicholson_delta_ep,
    nicholson_psi,
    nicholson_rate_constant,
    peak_potential_irreversible,
    randles_sevcik,
    randles_sevcik_irreversible,
    randles_sevcik_quasi,
)

__all__ = [
    "ButlerVolmerFitResult",
    "CottrellFitResult",
    "FitResult",
    "KouteckyLevichFitResult",
    "KouteckyLevichResult",
    "LevichFitResult",
    "MatsudaAyabeResult",
    "MicrodiscFitResult",
    "NicholsonResult",
    "RRDEResult",
    "RandlesSevcikFitResult",
    "SECMApproachFitResult",
    "TafelFitResult",
    "TafelResult",
    "anson",
    "butler_volmer",
    "butler_volmer_current_density",
    "butler_volmer_linear",
    "charge_transfer_resistance",
    "collection_efficiency",
    "cottrell",
    "cottrell_cylinder",
    "cottrell_spherical",
    "cottrell_step",
    "exchange_current",
    "exchange_current_density",
    "fit_butler_volmer",
    "fit_cottrell",
    "fit_curve",
    "fit_koutecky_levich",
    "fit_levich",
    "fit_linear",
    "fit_microdisc_transient",
    "fit_randles_sevcik",
    "fit_secm_approach",
    "fit_tafel",
    "fitting",
    "hydrodynamics",
    "kinetics",
    "koutecky_levich",
    "koutecky_levich_analysis",
    "levich",
    "levich_constant",
    "mahon_oldham_transient",
    "matsuda_ayabe",
    "matsuda_ayabe_lambda",
    "microband_limiting_current",
    "microdisc_limiting_current",
    "microdisc_transient",
    "microelectrodes",
    "microhemisphere_limiting_current",
    "microsphere_limiting_current",
    "nernst",
    "nernst_diffusion_layer",
    "nernst_equilibrium_concentrations",
    "nernst_potential",
    "nernst_ratio",
    "nicholson_delta_ep",
    "nicholson_psi",
    "nicholson_rate_constant",
    "peak_potential_irreversible",
    "rad_s_to_rpm",
    "randles_sevcik",
    "randles_sevcik_irreversible",
    "randles_sevcik_quasi",
    "ring_collection_current",
    "ring_limiting_current",
    "rotating_ring_disk",
    "rpm_to_rad_s",
    "sand",
    "sand_potential",
    "sand_transition_time",
    "secm",
    "secm_approach_curve",
    "secm_approach_negative_feedback",
    "secm_approach_positive_feedback",
    "secm_limiting_current_infinite",
    "secm_tip_current",
    "shielding_factor",
    "step",
    "step_concentration_profile",
    "step_flux_profile",
    "tafel",
    "tafel_analysis",
    "tafel_overpotential",
    "tafel_slope",
    "voltammetry",
]
