"""Soft Potato: Electrochemical simulation and analysis toolkit in Python.

Examples
--------
Simulating 1D chemical diffusion using the SciPy Method of Lines solver:

>>> import numpy as np
>>> import softpotato as sp
>>> from softpotato.solver import DiffusionProblem, DirichletBC, get_solver
>>>
>>> # Define 1D grid and problem
>>> grid = np.linspace(0.0, 1.0, 50)
>>> problem = DiffusionProblem(
...     grid=grid,
...     diffusivity={"A": 1e-4},
...     boundary_conditions={"A": (DirichletBC(0.0), DirichletBC(1.0))},
...     initial_conditions={"A": 1.0},
... )
>>>
>>> # Select solver and integrate
>>> solver = get_solver("scipy_ivp")
>>> result = solver.solve(problem, t_span=(0.0, 1.0))
>>> result.success
True
>>> result["A"].shape
(101, 50)
"""

from . import analytical, constants, solver
from .analytical import (
    BenchmarkCaseResult,
    BenchmarkMetrics,
    BenchmarkSuiteResult,
    ButlerVolmerFitResult,
    ConvergenceResult,
    CottrellFitResult,
    FitResult,
    KouteckyLevichFitResult,
    KouteckyLevichResult,
    LevichFitResult,
    MatsudaAyabeResult,
    MicrodiscFitResult,
    NicholsonResult,
    RandlesSevcikFitResult,
    RRDEResult,
    SECMApproachFitResult,
    TafelFitResult,
    TafelResult,
    anson,
    butler_volmer,
    butler_volmer_current_density,
    butler_volmer_linear,
    charge_transfer_resistance,
    collection_efficiency,
    compute_error_metrics,
    cottrell,
    cottrell_cylinder,
    cottrell_spherical,
    cottrell_step,
    estimate_convergence_order,
    exchange_current,
    exchange_current_density,
    fit_butler_volmer,
    fit_cottrell,
    fit_curve,
    fit_koutecky_levich,
    fit_levich,
    fit_linear,
    fit_microdisc_transient,
    fit_randles_sevcik,
    fit_secm_approach,
    fit_tafel,
    koutecky_levich,
    koutecky_levich_analysis,
    levich,
    levich_constant,
    list_benchmark_cases,
    mahon_oldham_transient,
    matsuda_ayabe,
    matsuda_ayabe_lambda,
    microband_limiting_current,
    microdisc_limiting_current,
    microdisc_transient,
    microhemisphere_limiting_current,
    microsphere_limiting_current,
    nernst,
    nernst_diffusion_layer,
    nernst_equilibrium_concentrations,
    nernst_potential,
    nernst_ratio,
    nicholson_delta_ep,
    nicholson_psi,
    nicholson_rate_constant,
    peak_potential_irreversible,
    rad_s_to_rpm,
    randles_sevcik,
    randles_sevcik_irreversible,
    randles_sevcik_quasi,
    ring_collection_current,
    ring_limiting_current,
    rotating_ring_disk,
    rpm_to_rad_s,
    run_benchmark,
    run_benchmark_suite,
    run_cottrell_benchmark,
    run_fourier_decay_benchmark,
    run_mass_conservation_benchmark,
    sand,
    sand_potential,
    sand_transition_time,
    secm_approach_curve,
    secm_approach_negative_feedback,
    secm_approach_positive_feedback,
    secm_limiting_current_infinite,
    secm_tip_current,
    shielding_factor,
    step_concentration_profile,
    step_flux_profile,
    tafel,
    tafel_analysis,
    tafel_overpotential,
    tafel_slope,
    verify_spatial_convergence,
    verify_temporal_convergence,
)
from .constants import (
    AVOGADRO,
    BOLTZMANN,
    ELEMENTARY_CHARGE,
    FARADAY,
    GAS_CONSTANT,
    STANDARD_TEMPERATURE,
    T_STD,
    VACUUM_PERMITTIVITY,
    F,
    R,
)
from .solver import (
    BaseSolver,
    BoundaryCondition,
    DiffusionProblem,
    DirichletBC,
    NeumannBC,
    SolverResult,
    get_solver,
    list_solvers,
)

__version__ = "3.0.0"

__all__ = [
    "AVOGADRO",
    "BOLTZMANN",
    "ELEMENTARY_CHARGE",
    "FARADAY",
    "GAS_CONSTANT",
    "STANDARD_TEMPERATURE",
    "T_STD",
    "VACUUM_PERMITTIVITY",
    "BaseSolver",
    "BenchmarkCaseResult",
    "BenchmarkMetrics",
    "BenchmarkSuiteResult",
    "BoundaryCondition",
    "ButlerVolmerFitResult",
    "ConvergenceResult",
    "CottrellFitResult",
    "DiffusionProblem",
    "DirichletBC",
    "F",
    "FitResult",
    "KouteckyLevichFitResult",
    "KouteckyLevichResult",
    "LevichFitResult",
    "MatsudaAyabeResult",
    "MicrodiscFitResult",
    "NeumannBC",
    "NicholsonResult",
    "R",
    "RRDEResult",
    "RandlesSevcikFitResult",
    "SECMApproachFitResult",
    "SolverResult",
    "TafelFitResult",
    "TafelResult",
    "__version__",
    "analytical",
    "anson",
    "butler_volmer",
    "butler_volmer_current_density",
    "butler_volmer_linear",
    "charge_transfer_resistance",
    "collection_efficiency",
    "compute_error_metrics",
    "constants",
    "cottrell",
    "cottrell_cylinder",
    "cottrell_spherical",
    "cottrell_step",
    "estimate_convergence_order",
    "exchange_current",
    "exchange_current_density",
    "fit_butler_volmer",
    "fit_cottrell",
    "fit_curve",
    "fit_koutecky_levich",
    "fit_levich",
    "fit_linear",
    "fit_microdisc_transient",
    "fit_randles_sevcik",
    "fit_secm_approach",
    "fit_tafel",
    "get_solver",
    "koutecky_levich",
    "koutecky_levich_analysis",
    "levich",
    "levich_constant",
    "list_benchmark_cases",
    "list_solvers",
    "mahon_oldham_transient",
    "matsuda_ayabe",
    "matsuda_ayabe_lambda",
    "microband_limiting_current",
    "microdisc_limiting_current",
    "microdisc_transient",
    "microhemisphere_limiting_current",
    "microsphere_limiting_current",
    "nernst",
    "nernst_diffusion_layer",
    "nernst_equilibrium_concentrations",
    "nernst_potential",
    "nernst_ratio",
    "nicholson_delta_ep",
    "nicholson_psi",
    "nicholson_rate_constant",
    "peak_potential_irreversible",
    "rad_s_to_rpm",
    "randles_sevcik",
    "randles_sevcik_irreversible",
    "randles_sevcik_quasi",
    "ring_collection_current",
    "ring_limiting_current",
    "rotating_ring_disk",
    "rpm_to_rad_s",
    "run_benchmark",
    "run_benchmark_suite",
    "run_cottrell_benchmark",
    "run_fourier_decay_benchmark",
    "run_mass_conservation_benchmark",
    "sand",
    "sand_potential",
    "sand_transition_time",
    "secm_approach_curve",
    "secm_approach_negative_feedback",
    "secm_approach_positive_feedback",
    "secm_limiting_current_infinite",
    "secm_tip_current",
    "shielding_factor",
    "solver",
    "step_concentration_profile",
    "step_flux_profile",
    "tafel",
    "tafel_analysis",
    "tafel_overpotential",
    "tafel_slope",
    "verify_spatial_convergence",
    "verify_temporal_convergence",
]
